# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: new-pool

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CmdLine@2
  inputs:
    script: 'docker build -t myimage .'

- task: CmdLine@2
  inputs:
    script: 'docker run -itd --name c1 -p 8000:8000 myimage'
